### ISSUE TITLE
初始化报错

### ISSUE THREAD

**Issue by daofeng2015** [DanmakuTree/DanmakuTree#39]
G:\bilibili-danmu\DanmakuTree\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release ) 
gyp ERR! find Python 
gyp ERR! find Python checking Python explicitly set from command line or npm configuration
gyp ERR! find Python - "--python=" or "npm config get python" is "C:\Users\刀锋\.windows-build-tools\python27\python.exe"
gyp ERR! find Python - executable path is "C:\Users\����\.windows-build-tools\python27\python.exe"
gyp ERR! find Python - "C:\Users\����\.windows-build-tools\python27\python.exe" could not be run
gyp ERR! find Python checking Python explicitly set from environment variable PYTHON
gyp ERR! find Python - process.env.PYTHON is "C:\Users\刀锋\.windows-build-tools\python27\python.exe"
gyp ERR! find Python - executable path is "C:\Users\����\.windows-build-tools\python27\python.exe"
gyp ERR! find Python - "C:\Users\����\.windows-build-tools\python27\python.exe" could not be run
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is "C:\Users\����\AppData\Local\Programs\Python\Python38\python.exe"
gyp ERR! find Python - "C:\Users\����\AppData\Local\Programs\Python\Python38\python.exe" could not be run
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - executable path is "C:\Users\����\.windows-build-tools\python27\python.exe"
gyp ERR! find Python - "C:\Users\����\.windows-build-tools\python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd G:\bilibili-danmu\DanmakuTree\node_modules\better-sqlite3
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.0 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the better-sqlite3@7.1.0 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

报错信息
好像是python环境相关的东西

**Comment by shugen002** [comment]
兄弟，我觉得你没装python，然后node-gyp就炸了。。。

我们这边有个better-sqlite3，是一个native的模块，需要node-gyp编译一下。

**Comment by daofeng2015** [comment]
> 兄弟，我觉得你没装python，然后node-gyp就炸了。。。
> 
> 我们这边有个better-sqlite3，是一个native的模块，需要node-gyp编译一下。
> 
> 建议阅读：https://github.com/nodejs/node-gyp#installation

我装了python的啊
![image](https://user-images.githubusercontent.com/14891398/86248772-e955bc80-bbe0-11ea-9c70-2fdadd0214e2.png)

**Comment by shugen002** [comment]
手动设置一下环境变量，node-gyp的搜索python机制有点傻，，，，

建议阅读：https://github.com/nodejs/node-gyp#on-windows

**Comment by daofeng2015** [comment]
> 手动设置一下环境变量，node-gyp的搜索python机制有点傻，，，，
> 
> 建议阅读：https://github.com/nodejs/node-gyp#on-windows

为啥python2这个环境就是设置不了....python3已经搞定了...
checking Python explicitly set from command line or npm configuration
gyp ERR! find Python - "--python=" or "npm config get python" is "C:\Users\刀锋\.windows-build-tools\python27\python.exe"
gyp ERR! find Python - executable path is "C:\Users\����\.windows-build-tools\python27\python.exe"
gyp ERR! find Python - "C:\Users\����\.windows-build-tools\python27\python.exe" could not be run
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is "C:\Users\����\AppData\Local\Programs\Python\Python38\python.exe"
gyp ERR! find Python - "C:\Users\����\AppData\Local\Programs\Python\Python38\python.exe" could not be run
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - executable path is "C:\Users\����\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe"
gyp ERR! find Python - "C:\Users\����\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe" could not be run
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - executable path is "C:\Users\����\.windows-build-tools\python27\python.exe"
gyp ERR! find Python - "C:\Users\����\.windows-build-tools\python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run

**Comment by ax4** [comment]
问题的主要原因是因为：
1. 开发环境路径当中包含 unicode, 非 ascii 码的问题, 占问题 70%
2. python27 (python 2.7) 的安装路径配置不正确, 占问题 30% 

经过讨论，目前已经修好了 python27 / python3 路径到 node-gyp 设置的问题，已经可以使得 `npm i` 走过 python 路径不正确这一步了，但是 better-sqlite3 作为一个 native 模块目前尚不存在 released prebuilt binaries, 因此在这种情况下会执行 `better-sqlite3@7.1.0 build-release 'node-gyp rebuild --release'` . 而这一步出现了 `Error: Unicode characters in the path` 的报错。

目前和后一步报错相关的 issues tracking 请移步 ( 防 issues url 链接定向故使用 code insertion) :
``` avoid url
https://github.com/JoshuaWise/better-sqlite3/issues/416
https://github.com/nodejs/node-gyp/issues/2157
https://github.com/nodejs/node-gyp/blob/a6b76a8b488c3ca3ee39f4138644593075c25306/gyp/pylib/gyp/easy_xml.py
```

目前我们谨慎建议开发者，在使用自己的开发环境时，避免出现中文（俄语/波兰语等也是如此）的非英文 ascii 路径名与系统用户名，这也与 windows / linux / macos 的系统安装过程有关系，我们暂时不对与**开发环境**出现的特殊报错进行保证。我们愿意提供帮助，但配置开发环境是每一个开发者自己的职责。

另外如果开发者遇到这类环境敏感的问题，且**因为自身工作环境**容易出现项目之间依赖冲突的问题，建议使用虚拟机 / 物理服务器 / docker-linux-container / docker-windows-container 来解决开发环境的问题，搭建一个更沙盒更隔离更干净的开发环境。同时注意，我们使用的 Electron 应用的开发已经降低了对于环境的需求，但仍不排除由于上述原因产生的特殊环境问题。

针对上面描述的 ascii 路径的问题，我们会继续保持观察和 tracking。
